import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
import os

def Mail_send(mailid, image_paths):
    # Set up the SMTP server
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(os.getenv('EMAIL_HOST_USER'), os.getenv('EMAIL_HOST_PASSWORD'))

    # Create a multipart message
    msg = MIMEMultipart()

    # Set email sender and receiver
    msg['From'] = 'saurabhmanepython@gmail.com'
    msg['To'] = mailid

    # Set the subject
    msg['Subject'] = "Demo Flat"

    # Attach the message body
    body = 'This mail is autogenerated by Saurabh_Mane'
    msg.attach(MIMEText(body, 'plain'))

    # Attach the image
    for image_path in image_paths:
        with open(image_path, 'rb') as img_file:
            img = MIMEImage(img_file.read())
            img.add_header('Content-Disposition', 'attachment', filename=image_path)
            msg.attach(img)


    server.send_message(msg)
    print('Mail sent Successfully')

    # Terminate the SMTP session
    server.quit()

